apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: 381112450421.dkr.ecr.eu-north-1.amazonaws.com/inventory-service:latest
        ports:
        - containerPort: 4000
