name: Build and Deploy Service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 381112450421.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        run: |
          docker build -t ${{ inputs.service_name }} ./${{ inputs.service_path }}

      - name: Tag image
        run: |
          docker tag ${{ inputs.service_name }}:latest \
          $ECR_REGISTRY/${{ inputs.service_name }}:$IMAGE_TAG

      - name: Push image
        run: |
          docker push $ECR_REGISTRY/${{ inputs.service_name }}:$IMAGE_TAG

      - name: Update deployment
        run: |
          sed -i "s|image: .*${{ inputs.service_name }}.*|image: $ECR_REGISTRY/${{ inputs.service_name }}:$IMAGE_TAG|g" \
          k8s/${{ inputs.service_name }}/deployment.yaml

      - name: Commit changes
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Update ${{ inputs.service_name }} image $IMAGE_TAG" || echo "No changes"
          git push
