name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 381112450421.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      # ---------- FRONTEND ----------
      - name: Build & Push Frontend
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest $ECR_REGISTRY/frontend:$IMAGE_TAG
          docker push $ECR_REGISTRY/frontend:$IMAGE_TAG

      # ---------- USER ----------
      - name: Build & Push User Service
        run: |
          docker build -t user-service ./user-service
          docker tag user-service:latest $ECR_REGISTRY/user-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/user-service:$IMAGE_TAG

      # ---------- ORDER ----------
      - name: Build & Push Order Service
        run: |
          docker build -t order-service ./order-service
          docker tag order-service:latest $ECR_REGISTRY/order-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/order-service:$IMAGE_TAG

      # ---------- INVENTORY ----------
      - name: Build & Push Inventory Service
        run: |
          docker build -t inventory-service ./inventory-service
          docker tag inventory-service:latest $ECR_REGISTRY/inventory-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/inventory-service:$IMAGE_TAG

      # ---------- NOTIFICATION ----------
      - name: Build & Push Notification Service
        run: |
          docker build -t notification-service ./notification-service
          docker tag notification-service:latest $ECR_REGISTRY/notification-service:$IMAGE_TAG
          docker push $ECR_REGISTRY/notification-service:$IMAGE_TAG

      # ---------- UPDATE MANIFESTS ----------
      - name: Update Kubernetes manifests
        run: |
          sed -i "s|image: .*frontend.*|image: $ECR_REGISTRY/frontend:$IMAGE_TAG|g" k8s/frontend/deployment.yaml
          sed -i "s|image: .*user-service.*|image: $ECR_REGISTRY/user-service:$IMAGE_TAG|g" k8s/user-service/deployment.yaml
          sed -i "s|image: .*order-service.*|image: $ECR_REGISTRY/order-service:$IMAGE_TAG|g" k8s/order-service/deployment.yaml
          sed -i "s|image: .*inventory-service.*|image: $ECR_REGISTRY/inventory-service:$IMAGE_TAG|g" k8s/inventory-service/deployment.yaml
          sed -i "s|image: .*notification-service.*|image: $ECR_REGISTRY/notification-service:$IMAGE_TAG|g" k8s/notification-service/deployment.yaml

      - name: Commit & push
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Update images to $IMAGE_TAG" || echo "No changes"
          git push
