name: CI - Build & Push Microservices

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 381112450421.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - frontend
          - user-service
          - order-service
          - inventory-service
          - notification-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.service }} ./${{ matrix.service }}

      - name: Tag image
        run: |
          docker tag ${{ matrix.service }}:latest \
          $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG

      - name: Push image to ECR
        run: |
          docker push $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG
