name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 381112450421.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - frontend
          - user-service
          - order-service
          - inventory-service
          - notification-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.service }} ./${{ matrix.service }}

      - name: Tag Docker image
        run: |
          docker tag ${{ matrix.service }}:latest \
          $ECR_REGISTRY/${{ matrix.service }}:${{ env.IMAGE_TAG }}

      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY/${{ matrix.service }}:${{ env.IMAGE_TAG }}

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Update all deployments
        run: |
          sed -i "s|image: .*frontend.*|image: $ECR_REGISTRY/frontend:$IMAGE_TAG|g" k8s/frontend/deployment.yaml
          sed -i "s|image: .*user-service.*|image: $ECR_REGISTRY/user-service:$IMAGE_TAG|g" k8s/user-service/deployment.yaml
          sed -i "s|image: .*order-service.*|image: $ECR_REGISTRY/order-service:$IMAGE_TAG|g" k8s/order-service/deployment.yaml
          sed -i "s|image: .*inventory-service.*|image: $ECR_REGISTRY/inventory-service:$IMAGE_TAG|g" k8s/inventory-service/deployment.yaml
          sed -i "s|image: .*notification-service.*|image: $ECR_REGISTRY/notification-service:$IMAGE_TAG|g" k8s/notification-service/deployment.yaml

      - name: Commit and push
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Update images to $IMAGE_TAG" || echo "No changes"
          git push
